pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        S3_BUCKET = "incident-frontend-808808151714-ap-south-1-an"
        BUILD_DIR = "dist"
        // Optional if using CloudFront
        CLOUDFRONT_DISTRIBUTION_ID = "ELIEM9C9UBACM"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('incident-frontend') {
                    sh '''
                    npm ci
                    '''
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('incident-frontend') {
                    sh '''
                    npm run build
                    '''
                }
            }
        }

        stage('Deploy to S3') {
            steps {
                dir('incident-frontend') {
                    sh '''
                    aws s3 sync $BUILD_DIR s3://$S3_BUCKET --delete --region $AWS_REGION
                    '''
                }
            }
        }

        stage('Invalidate CloudFront Cache') {
            when {
                expression {
                    return env.CLOUDFRONT_DISTRIBUTION_ID?.trim()
                }
            }
            steps {
                sh '''
                aws cloudfront create-invalidation \
                  --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
                  --paths "/*"
                '''
            }
        }
    }

    post {
        success {
            echo "Frontend deployed successfully to S3"
        }
        failure {
            echo "Frontend deployment failed"
        }
    }
}
