apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-backend
  template:
    metadata:
      labels:
        app: incident-backend
    spec:
      containers:
      - name: incident-backend
        image: 808808151714.dkr.ecr.ap-south-1.amazonaws.com/incident-backend:latest
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
        ports:
        - containerPort: 8000

